# Generated by Django 5.1.4 on 2024-12-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=100)),
                ('rate', models.FloatField()),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
